name: 'Dependency Review'
on: [pull_request]

permissions: 
  pull-requests: write
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
      
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Run script'
        run: script example_session
        
      - name: 'Dependency Review'
        id: dependency-review
        uses: actions/dependency-review-action@v3
        with:
          comment-summary-in-pr: true
      - name: test
        run: |
          exit
          cat example_session
        

