name: 'Dependency Review'
on: [pull_request]

permissions: 
  pull-requests: write
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v3
        with:
          fail-on-severity: moderate
          comment-summary-in-pr : true
          
          
  job2:
    runs-on: ubuntu-latest
    needs: dependency-review
    
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
        run: echo "$OUTPUT1"
