name: 'Dependency Review'
on: [pull_request]

permissions: 
  pull-requests: write
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
      
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Run script'
        run: script example_session
        
      - name: 'Dependency Review'
        id: dependency-review
        uses: actions/dependency-review-action@v3
        with:
          comment-summary-in-pr: true
      - name: Append to the comment 
        uses: marocchino/sticky-pull-request-comment@v2
        if: always()
        with:
          append: true
          message : |
            test, test ,test
            
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@v36.0.0
        if: always()
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}


        

