name: 'Dependency Review'
on: [pull_request]

permissions: 
  pull-requests: write
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.dependency-review.outputs.log-output }}
      
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        id: dependency-review
        uses: actions/dependency-review-action@v3
        with:
          comment-summary-in-pr: true
        env:
          LOG_OUTPUT: ${{ steps.dependency-review.outputs.log-output }}
  
  job2:
    runs-on: ubuntu-latest
    needs: dependency-review
    if: always()
    steps:
      - name: 'Print Log Output'
        run: echo "${{needs.dependency-review.env.LOG_OUTPUT}}"
